### ISSUE TITLE
multiple ped's spawning 

### ISSUE THREAD

**Issue by daveyboiigames** [trclassic92/tr-blackmarket#1]
**Describe the bug**
Hi i have a issue at the moment where multiple pes's are spawning on each other at the location

**Comment by trclassic92** [comment]
Can you please follow the bug report template. :)

**Comment by trclassic92** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1.
2.
3.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
- QBCore Version (Old/New)
- Have you tried fixing the problem on your own?

**Additional context**
Add any other context about the problem here.

**Comment by trclassic92** [comment]
> **Describe the bug** Hi i have a issue at the moment where multiple pes's are spawning on each other at the location

Try the lastest commit and see if that fixes your issue
